### ISSUE TITLE
Implement CRYPTOGRAPHY service for ONE cipher method using flask, standalone project

### ISSUE THREAD

**Issue by ivario123** [ivario123/NGAC_ABE#18]
# Implement crypto service for one rabe cypher

there needs to be a system for encrypting a string of text based on a user ID.

## Task description

The system should have 4 endpoints:
- [x] `url/make_file` POST a JSON containing path and returns 200 if ok.
- [x] `url/delete_file` POST a JSON containing a path and returns 200 if ok.
- [x] `url/encrypt_file` POST a JSON containing a policy, a file path and a string of text to encrypt, returns 200 if ok.
- [x] `url/decrypt_file` POST a JSON containing either a user_id or a list of attributes and a file name, returns file if ok.

The system should not do the encryption, it should call the encryption library #19. The system in this version should not depend on any other services, it should store files in a dictionary on the server.

## Task checklist

- [x] Set up the endpoints.
- [x] Store string in a dictionary, indexed by path
- [x] Generate static keys and read/write them from/to the file
- [x] Use the cryptography library to encrypt/decrypt files.
- [x] Use NGAC API to get the user attributes of the NGAC server

## Task Completion test

To consider the task complete all of the endpoints should exist and respond in the expected manner. Moreover, the data should be stored either on the cryptography server or on the remote storage server, the data should be properly encrypted using the RABE library
