### ISSUE TITLE
Create storage server, [READ, WRITE, DELETE] using flask and a dictionary

### ISSUE THREAD

**Issue by ivario123** [ivario123/NGAC_ABE#20]
# Implement a remote storage server

There needs to be a system for the long-term storage of encrypted files.

## Task description

The system should have 4 endpoints:
- [ ] `url/make_file` POST a JSON containing path and returns 200 if ok.
- [ ] `url/delete_file` POST a JSON containing a path and returns 200 if ok.
- [ ] `url/write_file` POST a JSON containing a file path and a string of text to store, returns 200 if ok.
- [ ] `url/read_file` POST a JSON containing a file name, returns file if ok.

The system can store files as actual files, but it is also ok to store the files less permanently and store them in a dictionary since this is proof of concept.

## Task checklist

- [ ] Set up the endpoints.
- [ ] Store string in a dictionary, indexed by path

## Task Completion test

To consider the task complete all of the endpoints should exist and respond in the expected manner.
