### ISSUE TITLE
Implement NGAC abstraction

### ISSUE THREAD

**Issue by ivario123** [ivario123/NGAC_ABE#4]
# Implement NGAC abstraction 
Make a wrapper that makes it easy to implement NGAC 

## Task description
Implement a user wrapper class, object wrapper, policy engine 

## Task checklist
- [x] Compile the prolog code to executables and run the examples
- [x] Implement an attribute abstraction
- [x] Implement a recourse abstraction 
- [x] Implement a policy abstraction 

## Task Completion test
Translate [tog-ngac in prolog](https://github.com/tog-rtd/tog-ngac-crosscpp) to python code

**Comment by ivario123** [comment]
I think we need some boilerplate that allows us to spin up the server and add some simple relations. I think that I can start working on this.

**Comment by ivario123** [comment]
For atribute abstractions I imagine an api like
```python
class Attribute:
  def __init__(self,attr:Str):
    self.attr = attr
  def get_attr(self) -> Str:
    return self.attr

ua1 = Attribute("Lärare")
oa1 = Attribute("Betyg")

```
This will later be combined into a set of policies

**Comment by ivario123** [comment]
> 

To test this, we should do 
```python
ua1 = Attribute("Lärare")
assert ua1.get_attr() == "Lärare"
```

**Comment by ivario123** [comment]
Also found this, https://github.com/wilkru-7/NGAC-CrossCPP it has better instructions on starting the server

**Comment by ivario123** [comment]
# Boilerplate
## Status
The latest commit ( f4a9f0337aeed214fe4be61eb6c1834d075936db ) created (Linux) executable files in the main repo. If you want to run the servers on windows just clone the new and improved [repo](https://github.com/ivario123/tog-ngac-crosscpp) and run the commands in this order

```powershell
swipl -v -o cme -g cme -c cme_sim.pl  #  Compile the CME server
swipl -v -o ngac -g ngac -c ngac.pl  # Compile the NGAC policy machine
swipl -v -o ngac_server -g ngac_server -c ngac.pl  # Compile the NGAC server
cd PEP-RAP
swipl -v -o pep -g pep -c pep.pl  # Compile the main PEP module
swipl -v -o pep_server -g pep_server -c pep.pl  # Compile the PEP server

# Now run all of the servers
./pep_server.exe  # Run PEP
cd ..
./cme.exe  # Run CME
./ngac_server.exe  # Run main ngac server, depends on the previous 2
```
All of the runners will ask for network access, this is fine since they are running local servers.
## Next step

The next step in the process will be to write some python abstraction, my goal is an api like

```python
# Create a new NGAC engine
ngac = NGAC(setup_params) # Ideally we would skip setup params, but we might need to pass args to the server or the path to the executable

# Create a set of user attributes
ua = attribute.from_list(["Teacher","Student","HeadMaster"]) # Some better atributes maybe

# Create a set of object attributes
oa = attribute.from_list(["Oa1","Oa2"])


# Create a set of policies
policies = policy.from_list([("Access",Ua[0],Oa[1]),("Write",Ua[1],Oa[1])])

# Determine what type of we want to add from type arguments
ngac.new(ObjectAttribute, oa) # Ideally passing anny itter with the object attributes should work
ngac.new(UserAttribute, ua)
ngac.new(Policy, policies)
```
To add a new user we should do something like this
```python
user = User() # Could have a set of optional arguments
user.assign_attr(["Teacher","Student"])
# Insert the user into the ngac tables
ngac.new(User,user) # This should return error when a non valid attribute is used
``` 
To add a new resource we should do something like
```python
resource = Resource() # Could have a set of optional arguments, like value,name,attributes etc
user.assign_attr("Oa1") # Should not need to be list
# Insert the new resource into NGAC
ngac.new(Resource,resource) # This should return error when a non valid attribute is used
```

And to check if a user has the correct rights to a resource we should do something like
```python
ngac.verify(user = some_user, resource = some_resource)
```
this should work since the user has all it's attributes stored, and the resource has all of it attributes stored

Thoughts? @sanlju
