### ISSUE TITLE
Implement [RABE](https://github.com/Fraunhofer-AISEC/rabe) wrapper in python [ ABE ]

### ISSUE THREAD

**Issue by ivario123** [ivario123/NGAC_ABE#5]
# Implement ABE abstraction
Make a good wrapper that makes it easy to implement ABE policies

## Task description
The task is to implement a simple wrapper that includes functionality to remove/add policies, get user attributes get policy requirements

## Task checklist
- [ ] Implement a attribute abstraction
- [ ] Implement a resource abstraction
- [ ] Implement a policy abstraction

## Task Completion test
Should act the same as [the abe implementation](https://github.com/sagrawal87/ABE/blob/master/samples/main.py), we need unit tests

**Comment by ivario123** [comment]
I Think that we should add a todo point,
- [ ] Basic example for calling both versions of ABE

**Comment by ivario123** [comment]
I think that this should be considered done, at least for sprint 1 since we have all the cyphers that we will need.

**Comment by ivario123** [comment]
At least after @Klas-Norling has merged his changes to https://github.com/Klas-Norling/Cryptography/
